# .yaml files in this directory are executed workflows:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# This workflow is triggered on pushes to non-main (or master) branches
# Builds and tests the app (just test)
name: Publish new tagged version

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    tags:
      - "v*"
    # branches:
    #   - "main"

jobs:
  on-tag-version:
    name: Trigger publish on version tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup just
        uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.32.1

      - name: on-tag-version
        run: just on-tag-version
